# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_artigocientifico_autores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='artigos',
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(to='eventos.Autor'),
        ),
    ]
